---
# tasks file for mysql
- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest

- name: Install MySQL
  apt: name={{item}} state=present
  with_items:
  - python-mysqldb
  - mysql-server

- name: Start MySQL Service
  service: name=mysql state=started enabled=yes

- name: Create mysql database
  become: true
  mysql_db: 
    name={{ wp_mysql_db }} 
    state=present 
    # These are no longer required as we set /root/.my.cnf
    # login_user=root 
    # login_password=""

- name: Update MySQL Password
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    check_implicit_admin: yes
    priv: "*.*:All,GRANT"
  with_items:
  - vm9
  - 192.168.56.101
  - ::1
  - localhost

- name: Create mysql user
  # @todo In Ubuntu 16, this doesn't work
  # We have to run something like
  # `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test';`
  become: true
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL
    # These are no longer required as we set /root/.my.cnf
    # login_user=root 
    # login_password="" 

