---

- name: "Create administrador group"
  become: true
  group:
    name: "administrador"
    state: present

- name: "Create AdminPruebas account"
  become: true
  user:
    name: "AdminPruebas"
    state: present
    group: "administrador"
    uid: "1220"
    comment: "Administrador Pruebas"
    password: "{{ 'AdMinistRat0r1' | password_hash('sha512') }}"
    expires: "-1"
    shell: "/bin/bash"

- name: "Create UsuarioPruebas account"
  become: true
  user:
    name: "UsuarioPruebas"
    state: present
    uid: "1221"
    comment: "Usuario Pruebas"
    password: "{{ 'USeRPruEBas00' | password_hash('sha512') }}"
    expires: "-1"
    shell: "/bin/bash"

- name: "Set password expiration days limit"
  become: true
  raw: "chage -M 365 {{ item.username }}"
  with_items: "{{ users }}"

- name: "Touch administrador file"
  become: true
  file:
    path: "/etc/sudoers.d/administrador"
    state: touch
    mode: "0644"
    owner: "root"
    group: "root"

- name: "Allow users of administrador group to sudo without a password"
  become: true
  lineinfile:
    dest: "/etc/sudoers.d/administrador"
    state: present
    line: "%administrador ALL=(ALL) NOPASSWD: ALL"