---

- name: redhat | Installing Firewalld
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'cockpit'
    - 'firewall-config'
    - 'firewalld'

- name: redhat | Ensuring firewalld Service Is Started And Enabled On Boot
  service:
    name: "firewalld"
    state: "started"
    enabled: true
  become: true
