---
- name: rules | Managing Firewall Rules
  firewalld:
    immediate: "{{ item['immediate']|default(omit) }}"
    interface: "{{ item['interface']|default(omit) }}"
    masquerade: "{{ item['masquerade']|default(omit) }}"
    permanent: "{{ item['permanent']|default(omit) }}"
    port: "{{ item['port']|default(omit) }}"
    service: "{{ item['service']|default(omit) }}"
    sources: "{{ item['sources']|default(omit) }}"
    state: "{{ item['state']|default(omit) }}"
    zone: "{{ item['zone']|default(omit) }}"
  become: true
  with_items: '{{ firewalld_rules }}'
