- name: template named.conf
  template:
    src: "/home/vagrant/roles/bind/templates/named.conf.j2"
    dest: /etc/bind/named.conf
    backup: yes

- name: setting up forward and reverse files
  template:
    src: "/home/vagrant/roles/bind/templates/named.conf.local.j2"
    dest: /etc/bind/named.conf.local
    backup: yes

- name: deploying forward config
  template:
    src: "/home/vagrant/roles/bind/templates/db.ctfprolab.es.j2"
    dest: /etc/bind/db.ctfprolab.es
    backup: yes
    
- name: deploying reverse config
  template:
    src: "/home/vagrant/roles/bind/templates/db.56.168.192.j2"
    dest: /etc/bind/db.56.168.192
    backup: yes

- service:
    name: bind9
    state: restarted